apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-backend
  template:
    metadata:
      labels:
        app: warehouse-backend
    spec:
      containers:
        - name: warehouse-backend
          image: sure777/warehouse-backend
          ports:
            - containerPort: 8080
